version: 2.1
orbs: 
  docker: circleci/docker@2.0.3
jobs:
  build:
    parameters:
      docker_image_tag:
        type: string
        default: "${CIRCLE_BUILD_NUM}"
    executor: docker/docker
    #working_directory: apps
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: cucumislush
          tag:  "<< parameters.docker_image_tag >>"
      - run:
          name: create directory
          command: mkdir -p frontends/images
      - persist_to_workspace:
          root: frontends
          paths:
            - "images"
  push_docker_image:
    parameters:
      docker_repo_name:
        type: string
        default: "${DOCKER_REPO_NAME}/cucumislush"
      docker_image_tag:
        type: string
        default: "${CIRCLE_BUILD_NUM}"
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/install-docker-tools
      - attach_workspace:
          at: frontends/images
      - run:
          name: login to docker
          command: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker/push:
          image: "<< parameters.docker_repo_name >>"
          tag: "<< parameters.docker_image_tag >>"
      #- run: sudo docker save -o 'cucumislushfrontend.tar' 'cucumislush:$CIRCLE_SHA1'
      

workflows:
  build_workflow:
    jobs:
      - build
      - push_docker_image:
          requires:
            - build
