version: 2.1
orbs: 
  docker: circleci/docker@2.0.3
jobs:
  build:
    executor: docker/docker
    #working_directory: apps
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: cucumislush
      - persist_to_workspace:
          root: frontends
          paths:
            - "images"
  save_docker_image:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - attach_workspace:
          at: frontends/images
      - run: sudo docker save -o 'cucumislushfrontend.tar' cucumislush
      

workflows:
  build_workflow:
    jobs:
      - build
      - save_docker_image:
          requires:
            - build
