version: 2
jobs:
  build:
    parameters:
      repo_name:
        type: string
        default: ${DOCKER_REPO_NAME}
    docker:
      - image: cimg/node:17.8.0
        environment:
          ENV_NAME: DEV
    steps:
      - checkout
      - run:
          name: Export Env Var
          command: |
            echo 'export TAG=${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=cucumislushfrontend' >> $BASH_ENV 

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: login to docker hub
          command: |
            sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
               
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_REPO_NAME/$IMAGE_NAME:$TAG .

      - run:
          name: Check List of docker image
          command: |
            echo 'checking to see if $DOCKER_REPO_NAME/$IMAGE_NAME:$TAG is present'
            docker image ls
            
      - run:
          name: Push Docker image
          command: docker push $DOCKER_REPO_NAME/$IMAGE_NAME:$TAG
workflows:
  version: 2
  build-docker:
    jobs:
      - build