<<<<<<< HEAD
version: 2.1
variables:
  repo_name: "${DOCKER_REPO_NAME}"
  image_tag: "${CIRCLE_BUILD_NUM}"
orbs:
  docker: circleci/docker@2.0.3
=======
version: 2
>>>>>>> f55991516106ceddd7c9eff8caa730086d941d27
jobs:
  build:
    parameters:
      repo_name:
        type: string
        default: ${DOCKER_REPO_NAME}
      image_tag:
        type: string
<<<<<<< HEAD
        default: "${DOCKER_REPO_NAME}/cucumislush"
    executor: docker/docker
    #working_directory: apps
=======
        default: ${CIRCLE_BUILD_NUM}
    docker:
      - image: cimg/node:17.8.0
        environment:
          ENV_NAME: DEV
>>>>>>> f55991516106ceddd7c9eff8caa730086d941d27
    steps:
      - checkout
<<<<<<< HEAD
      - docker/build:
          image: "<< parameters.docker_repo_name >>"
          tag: "<< parameters.docker_image_tag >>"
=======
>>>>>>> f55991516106ceddd7c9eff8caa730086d941d27
      - run:
          name: Export Env Var
          command: |
            echo 'export TAG=${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=cucumislushfrontend' >> $BASH_ENV

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: login to docker hub
          command: |
            sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
<<<<<<< HEAD
      - docker/push:
          image: "<< parameters.docker_repo_name >>"
          tag: "<< parameters.docker_image_tag >>"
      #- run: sudo docker save -o 'cucumislushfrontend.tar' 'cucumislush:$CIRCLE_SHA1'
=======

      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:$TAG .
      - run:
          name: Tag Image
          command: docker tag $IMAGE_NAME:$TAG "pihemcloud/conclase:cucumislushfrontend"

      - run:
          name: Check List of docker image
          command: |
            echo 'checking to see if $DOCKER_REPO_NAME/$IMAGE_NAME:$TAG is present'
            docker image ls
      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: Push Docker image
          command: docker push pihemcloud/conclase:cucumislushfrontend
  deploy:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $DEV_USER@$DEV_IP "./conclase-deploy.sh"
>>>>>>> f55991516106ceddd7c9eff8caa730086d941d27

workflows:
  version: 2
  build-docker:
    jobs:
<<<<<<< HEAD
      - build
      - push_docker_image:
=======
      - build:
          context:
            - conclase
      - deploy:
>>>>>>> f55991516106ceddd7c9eff8caa730086d941d27
          requires:
            - build
