version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: sudo apt update
      - run:
          name: install curl
          command: sudo apt install curl
      - run:
          name: get docker script
          command: curl -fsSL https://get.docker.com -o get-docker.sh
      - run:
          name: install docker with script
          command: sudo sh get-docker.sh
      - run:
          name: enable docker
          command: sudo systemctl enable docker.service
      - run:
          name: containerd
          command: sudo systemctl enable containerd.service
     # - run: sudo systemctl start docker
      - run:
          name: build docker image
          command: sudo docker build -t cucumislushfrontend . 

workflows:
  build_workflow:
    jobs:
      - build
