version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run: sudo docker build -t 'cucumislushfrontend:$CIRCLE_BUILD_NUM' .

workflows:
  build_workflow:
    jobs:
      - build
