version: 2.1
orbs: 
  docker: circleci/docker@2.0.3
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: cucumislush
      

workflows:
  build_workflow:
    jobs:
      - build
