import http from "../http-common";

export const createCart = async (cart) => {
  return await http.post("Cart/Create", cart);
};

export const getCartByUserId = async (id) => {
  return await http.get(`/Cart/ListCartItem?OwnerId=${id}`);
};

export const placeOrder = async (order) => {
  return await http.post(`/Cart/CreateOrder`, order);
};

const order = {
  statusCode: "0000",
  description: "request successfully executed",
  data: [
    {
      Id: "1650897223090",
      DateOrderered: "2022-04-25T14:33:43.090Z",
      OwnerId: "raimialiu428@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "40",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "Card",
      PaymentDetails: "Lagos",
      AdditionalInformation: [
        {
          Name: "Age",
          Value: 23,
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
    {
      Id: "1651507257154",
      DateOrderered: "2022-05-02T16:00:57.155Z",
      OwnerId: "test@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "100000",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "",
      PaymentDetails: "",
      AdditionalInformation: [
        {
          Name: "Paystack_Ref",
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
    {
      Id: "1651507350035",
      DateOrderered: "2022-05-02T16:02:30.035Z",
      OwnerId: "test@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "10000",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "",
      PaymentDetails: "",
      AdditionalInformation: [
        {
          Name: "Paystack_Ref",
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
    {
      Id: "1651508423881",
      DateOrderered: "2022-05-02T16:20:23.881Z",
      OwnerId: "test@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "200000",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "paystack",
      PaymentDetails: "",
      AdditionalInformation: [
        {
          Name: "Paystack_Ref",
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
    {
      Id: "1651511111588",
      DateOrderered: "2022-05-02T17:05:11.589Z",
      OwnerId: "test@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "200000",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "paystack",
      PaymentDetails: "",
      AdditionalInformation: [
        {
          Name: "Paystack_Ref",
          Value: "T063564585986162",
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
    {
      Id: "1651511260271",
      DateOrderered: "2022-05-02T17:07:40.271Z",
      OwnerId: "chioma@gmail.com",
      Status: "NEW",
      DateDelivered: null,
      TotalAmount: "320000",
      IsActive: true,
      DeliveryAddress: null,
      PaymentMethod: "paystack",
      PaymentDetails: "",
      AdditionalInformation: [
        {
          Name: "Paystack_Ref",
          Value: "T464663605326611",
        },
      ],
      OrderItems: [
        {
          Id: 1,
          ProductId: 2,
          BaseAmount: "20",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1650897223090",
          ProductInfo: {
            Id: 1,
            Name: "Shelter",
            Description: "this is shelter",
            CategoryId: 2,
            Kind: "IsMeasurable",
            Price: "200",
            IsDeleted: true,
            ImagesUrls: ["string"],
            EntryDate: "2022-04-25T12:23:50.352Z",
            UpdatedBy: null,
            CreeatedBY: "tunde",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 1,
                Name: "string",
                Value: "string",
                ProductId: 1,
              },
            ],
            ProductStore: {
              Id: 1,
              ProductId: 1,
              Quantity: 2,
              OutOfStock: false,
              EntryDate: "2022-04-25T12:23:50.352Z",
              UpdatedBy: null,
              CreeatedBY: "tunde",
              LastModifiedDate: null,
            },
            Category: {
              Id: 2,
              Name: "Shielding",
              IsActive: true,
              IsDeleted: true,
              EntryDdate: "2022-04-25T12:21:27.639Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "string",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 2,
          ProductId: 21,
          BaseAmount: "100000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507257154",
          ProductInfo: {
            Id: 2,
            Name: "Cabinet with sliding doors",
            Description:
              "Store things like papers, binders and chargers hidden behind the doors to enjoy a clutter-free space. Lockable storage for your private things. The back wall of the cabinet can be mounted to the back or middle of the cabinet if you want the cabinet to be accessible from both sides, with sliding doors on one side and open shelves on the other.\\n\\nThe freestanding cabinet is perfect to use as a divider between different activities in the same room. Creates privacy without blocking the workspace entirely and is great for small and large areas. The sliding doors are lockable, so you can keep your private belongings safe. You can adjust your storage according to your needs, as the shelves are adjustable. The storage unit stands steady also on uneven floors since it has adjustable feet. Possible to separate for recycling or energy recovery if available in your community.,\n",
            CategoryId: 8,
            Kind: "Direct",
            Price: "120000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651053527/products/t0pbzs8gasea89n6malr.png",
            ],
            EntryDate: "2022-04-27T09:59:16.018Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 2,
                Name: "Color",
                Value: "White",
                ProductId: 2,
              },
              {
                Id: 3,
                Name: "Weight",
                Value: "500",
                ProductId: 2,
              },
              {
                Id: 4,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 2,
              },
            ],
            ProductStore: {
              Id: 2,
              ProductId: 2,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T09:59:16.018Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 3,
          ProductId: 10,
          BaseAmount: "10000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651507350035",
          ProductInfo: {
            Id: 3,
            Name: "Staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "500000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651055227/products/ntgakl0gt4mkftesegks.jpg",
            ],
            EntryDate: "2022-04-27T10:33:24.416Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 5,
                Name: "Color",
                Value: "brown",
                ProductId: 3,
              },
              {
                Id: 6,
                Name: "Weight",
                Value: "300",
                ProductId: 3,
              },
              {
                Id: 7,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 3,
              },
            ],
            ProductStore: {
              Id: 3,
              ProductId: 3,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T10:33:24.416Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 4,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651508423881",
          ProductInfo: {
            Id: 4,
            Name: "Double shelf stack",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at...",
            CategoryId: 4,
            Kind: "Direct",
            Price: "60000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057646/products/nqojivbhpqumraybtgy4.png",
            ],
            EntryDate: "2022-04-27T11:08:28.996Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 8,
                Name: "Color",
                Value: "White",
                ProductId: 4,
              },
              {
                Id: 9,
                Name: "Weight",
                Value: "200",
                ProductId: 4,
              },
              {
                Id: 10,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 4,
              },
            ],
            ProductStore: {
              Id: 4,
              ProductId: 4,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:08:28.996Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 5,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511111588",
          ProductInfo: {
            Id: 5,
            Name: "Wall shelf",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 8,
            Kind: "Direct",
            Price: "100000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057739/products/dqolzabopgcx3psy4tgn.png",
            ],
            EntryDate: "2022-04-27T11:09:38.183Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 11,
                Name: "Color",
                Value: "white",
                ProductId: 5,
              },
              {
                Id: 12,
                Name: "Weight",
                Value: "60",
                ProductId: 5,
              },
              {
                Id: 13,
                Name: "IsInstallable",
                Value: "no",
                ProductId: 5,
              },
            ],
            ProductStore: {
              Id: 5,
              ProductId: 5,
              Quantity: 10,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:09:38.183Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 8,
              Name: "Furnitures",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:59.885Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 6,
          ProductId: 5,
          BaseAmount: "100000",
          Quantity: 2,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 6,
            Name: "brown luxury staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "400000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651057788/products/qqc26sauve9n15t8gk2u.jpg",
            ],
            EntryDate: "2022-04-27T11:30:26.186Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 14,
                Name: "Color",
                Value: "200",
                ProductId: 6,
              },
              {
                Id: 15,
                Name: "Weight",
                Value: "300",
                ProductId: 6,
              },
              {
                Id: 16,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 6,
              },
            ],
            ProductStore: {
              Id: 6,
              ProductId: 6,
              Quantity: 99,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:30:26.186Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
        {
          Id: 7,
          ProductId: 19,
          BaseAmount: "120000",
          Quantity: 1,
          RequiresInstalation: false,
          RequiresSupport: false,
          DiscountApplied: false,
          DiscountId: -1,
          OrderId: "1651511260271",
          ProductInfo: {
            Id: 7,
            Name: "Brown web staircase",
            Description:
              "A random placeholder description of a product sold in cucumislush that can be delivered straight to your home by our agents that are available every hour of the day. Shop for quality fabricated products at cucumislush.",
            CategoryId: 4,
            Kind: "OnInspection",
            Price: "4000000",
            IsDeleted: false,
            ImagesUrls: [
              "http://res.cloudinary.com/conclase/image/upload/v1651059358/products/ll8oatkgjuw7peerqeqj.jpg",
            ],
            EntryDate: "2022-04-27T11:36:06.926Z",
            UpdatedBy: null,
            CreeatedBY: "admin",
            LastModifiedDate: null,
            MetaData: [
              {
                Id: 17,
                Name: "Color",
                Value: "brown",
                ProductId: 7,
              },
              {
                Id: 18,
                Name: "Weight",
                Value: "200",
                ProductId: 7,
              },
              {
                Id: 19,
                Name: "IsInstallable",
                Value: "yes",
                ProductId: 7,
              },
            ],
            ProductStore: {
              Id: 7,
              ProductId: 7,
              Quantity: 199,
              OutOfStock: false,
              EntryDate: "2022-04-27T11:36:06.926Z",
              UpdatedBy: null,
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
            Category: {
              Id: 4,
              Name: "Stainless Steels",
              IsActive: true,
              IsDeleted: false,
              EntryDdate: "2022-04-27T09:41:08.048Z",
              CategoryType: "ProductCategory",
              UpdatedBy: "string",
              CreeatedBY: "admin",
              LastModifiedDate: null,
            },
          },
        },
      ],
    },
  ],
  hasNextPage: false,
  isSuccessful: true,
  currentPage: "1",
  hasPreviousPage: false,
  totalPages: 6,
  pageSize: "1",
  hasError: false,
  message: "listed",
  totalCount: 6,
};
